### ISSUE TITLE
Support for changing the default identifier

### ISSUE THREAD

**Issue by tgriesser** [DAB0mB/graphql-tag-pluck#10]
Gatsby currently requires that the template tag be named `graphql` for how they internally parse:
```ts
import { graphql } from 'gatsby'

export const query = graphql`
  query PageQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
`
```

It would be great if there were an option to configure the [defaultGqlIdentifierName](https://github.com/DAB0mB/graphql-tag-pluck/blob/8037ad17a9b97ccd86edda3340fd12f738c7028e/src/visitor.js#L4) to support this. I could open a PR if it's something you're up for.

**Comment by DAB0mB** [comment]
Yes an option can be provided via function options I don't see why not. A PR would be helpful indeed!

**Comment by DAB0mB** [comment]
Just added support for that as well as other stuff and released a new version. See [version 0.5.0 release notes](https://github.com/DAB0mB/graphql-tag-pluck/releases/tag/0.5.0).
