### ISSUE TITLE
typescript should be a peerDependency

### ISSUE THREAD

**Issue by ezpuzz** [DAB0mB/graphql-tag-pluck#11]
I believe typescript should be a peer dependency in package.json.  In my project I would not like to include additional versions of the entirety of typescript other than the version I have chosen for my project.

**Comment by DAB0mB** [comment]
I don't think it should be included as a peer dependency. Some people just don't wanna deal with TS at all. What we should do, instead, is to require TS dynamically based on what's available and if necessary. So we would have something like this:

```js
export const parse = (code, config) => {
  if (config.plugins.includes('typescript')) {
    const ts = require('typescript')

    // ...
  }
}
```

What do you think?

**Comment by alfaproject** [comment]
Either that or making it a peer dependency would be fine with me as well. Currently I need to keep deduplicating it manually in my project ):

**Comment by DAB0mB** [comment]
Fixed. Will soon release a version

**Comment by dozoisch** [comment]
@DAB0mB is it possible to release that fix :) thanks!
