### ISSUE TITLE
Expression statements do not work with trailing semicolons

### ISSUE THREAD

**Issue by mjbcopland** [DAB0mB/graphql-tag-pluck#27]
```javascript
const assert = require("assert");
const { gqlPluckFromCodeString } = require("graphql-tag-pluck");

assert.equal(gqlPluckFromCodeString("/* GraphQL */ `{}`"), "{}");
assert.equal(gqlPluckFromCodeString("/* GraphQL */ `{}`;"), "{}");
```

```
assert.equal(gqlPluckFromCodeString("/* GraphQL */ `{}`;"), "{}");
       ^
AssertionError [ERR_ASSERTION]: '{}`' == '{}'
```

&nbsp;

The whole expression statement node is passed to pluckStringFromFile() so when we go to trim the quotes [here](https://github.com/DAB0mB/graphql-tag-pluck/blob/master/src/visitor.js#L112), we actually trim the opening quote and trailing semicolon, leaving the closing quote in the output.

**Comment by ardatan** [comment]
Fixed in 0.8.3!
