### ISSUE TITLE
Escaped backticks should be unescaped in result

### ISSUE THREAD

**Issue by smeijer** [DAB0mB/graphql-tag-pluck#44]
When defining schemas in JS files, with the help of `gql`, we are required to escape any backticks in descriptions.

Those escape characters are only there in the js file. They shouldn't exists in grapql files, as that will throw an error (``Syntax Error: Invalid character escape sequence: \` ``) . And should imo also not be included in the output from `gqlPluckFromFile`.

Take a schema like:

```js
import gql from 'graphql-tag';

export default gql`
  type User { 
    id: ID! 
    "Choose a nice username, so users can \`@mention\` you."
    username: String! 
    email: String! 
  } 
`
```

I would expect the pluck result to be stripped from escape characters:

```graphql
type User { 
    id: ID! 
    "Choose a nice username, so users can `@mention` you."
    username: String! 
    email: String! 
} 
```

But instead, the escape characters are preserved:

```graphql
type User { 
    id: ID! 
    "Choose a nice username, so users can \`@mention\` you."
    username: String! 
    email: String! 
} 
```

See here for a small repo: https://repl.it/@smeijer/JointQuarrelsomeEquipment

The current output is an issue for me, as grapql-codegen uses the output as grapql, and the current output is not valid if the source contained these escaped back ticks.

See here for some background info:
https://github.com/dotansimha/graphql-code-generator/issues/2272

**Comment by ardatan** [comment]
Fixed in 0.8.4!
