### ISSUE TITLE
Importing { gql } from 'apollo-boost' isn't supported

### ISSUE THREAD

**Issue by bartlangelaan** [DAB0mB/graphql-tag-pluck#5]
This module works perfectly if you `import gql from 'graphql-tag'`.

However, when using the _apollo-boost_ package it's also possible to use the `import { gql } from 'apollo-boost'` syntax.

Of course a quick resolution is to use the other import mechanism, but it would be nice if all `gql` template literals would be parsed.

**Comment by DAB0mB** [comment]
Hey @bartlangelaan, I'll take a deeper look at the issues that you opened and your PRs, should be fixed soon.
